-- =====================================================================
-- 통장(계좌) 관리 (한 번만 실행)
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 Run.
--
-- 법인 통장/개인 통장처럼, 내역이 어느 통장에서 나간 돈인지 표시하고 필터링하는 기능.
-- 통장은 건물이 아니라 가족(ownerId) 단위로 관리한다 - 법인 통장 하나로 여러 건물의
-- 비용을 같이 낼 수도 있기 때문이다.
-- =====================================================================

create table if not exists "BankAccounts" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  name text not null,
  "createdAt" timestamp default now()
);

-- 같은 가족 안에서 통장 이름은 유일하게 (같은 이름으로 또 만들면 헷갈리니까).
create unique index if not exists "BankAccounts_ownerId_name_idx" on "BankAccounts" ("ownerId", "name");
create index if not exists "BankAccounts_ownerId_idx" on "BankAccounts" ("ownerId");

alter table "Ledger" add column if not exists "bankAccountId" bigint references "BankAccounts"(id) on delete set null;
alter table "LedgerTemplates" add column if not exists "bankAccountId" bigint references "BankAccounts"(id) on delete set null;

create index if not exists "Ledger_bankAccountId_idx" on "Ledger" ("bankAccountId");
create index if not exists "LedgerTemplates_bankAccountId_idx" on "LedgerTemplates" ("bankAccountId");

-- 다른 테이블들과 같은 보안 모델: RLS 켜고 정책은 안 만든다 (서버 service_role 전용).
alter table "BankAccounts" enable row level security;
