-- =====================================================================
-- 내역 하나가 여러 카테고리(요약표)에 동시에 속할 수 있도록 다대다로 변경 (한 번만 실행)
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 Run.
--
-- 지금까지: Ledger.reportId(단일 컬럼) - 내역 하나는 카테고리 하나에만 속함.
-- 바뀌는 것: LedgerReportLinks(연결 테이블)로, 내역 하나가 카테고리 여러 개에 속할 수 있음.
-- 기존 Ledger.reportId 값은 그대로 이 연결 테이블로 옮겨준다(데이터 안 날아감).
-- Ledger.reportId 컬럼은 당장 지우지 않고 남겨둔다(혹시 몰라서) - 이제 앱은 안 쓴다.
-- =====================================================================

create table if not exists "LedgerReportLinks" (
	id bigint generated by default as identity primary key,
	"ledgerId" bigint references "Ledger"(id) on delete cascade not null,
	"reportId" bigint references "LedgerReports"(id) on delete cascade not null,
	unique ("ledgerId", "reportId")
);

create index if not exists "LedgerReportLinks_ledgerId_idx" on "LedgerReportLinks" ("ledgerId");
create index if not exists "LedgerReportLinks_reportId_idx" on "LedgerReportLinks" ("reportId");

alter table "LedgerReportLinks" enable row level security;

-- 기존 단일 reportId 값을 연결 테이블로 이관
insert into "LedgerReportLinks" ("ledgerId", "reportId")
select id, "reportId" from "Ledger" where "reportId" is not null
on conflict ("ledgerId", "reportId") do nothing;
