-- =====================================================================
-- 요약표(카테고리)와 그룹을 화면에서 원하는 순서로 옮길 수 있도록 순서 컬럼/테이블 추가 (한 번만 실행)
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 Run.
--
-- 1) LedgerReports.sortOrder: 요약표 하나하나의 표시 순서. 지금까지 보이던 순서
--    (최근 등록순)를 그대로 유지하도록 미리 채워준다 - 실행해도 화면이 안 바뀐다.
-- 2) LedgerReportGroups: 그룹 이름 자체의 표시 순서. 기존 요약표에 쓰인 그룹 이름들을
--    각 그룹의 가장 앞선 요약표 순서를 물려받아 자동으로 만들어준다.
-- =====================================================================

alter table "LedgerReports" add column if not exists "sortOrder" integer;

update "LedgerReports" lr
set "sortOrder" = sub.rn
from (
	select id, row_number() over (partition by "bldId" order by "createdAt" desc) as rn
	from "LedgerReports"
) sub
where lr.id = sub.id and lr."sortOrder" is null;

alter table "LedgerReports" alter column "sortOrder" set default 0;
alter table "LedgerReports" alter column "sortOrder" set not null;

create table if not exists "LedgerReportGroups" (
	id bigint generated by default as identity primary key,
	"bldId" bigint references "Buildings"(id) on delete cascade not null,
	name text not null,
	"sortOrder" integer not null default 0,
	unique ("bldId", name)
);

create index if not exists "LedgerReportGroups_bldId_idx" on "LedgerReportGroups" ("bldId");

alter table "LedgerReportGroups" enable row level security;

insert into "LedgerReportGroups" ("bldId", name, "sortOrder")
select lr."bldId", g.name, min(lr."sortOrder")
from "LedgerReports" lr, unnest(lr."groupNames") as g(name)
group by lr."bldId", g.name
on conflict ("bldId", name) do nothing;
