-- =====================================================================
-- 커스텀 회계 요약표(리포트) 기능 (한 번만 실행)
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 Run.
--
-- 회계(전체 탭)에서 여러 내역을 검색해서 고르거나 직접 입력한 줄을 섞어
-- "총 비용" 같은 이름 붙은 요약표로 저장해두는 기능을 위한 테이블.
-- =====================================================================

-- 저장된 요약표 하나 (예: "총 비용", "김주이자")
create table if not exists "LedgerReports" (
  id bigint generated by default as identity primary key,
  "bldId" bigint references "Buildings"(id) on delete cascade not null,
  title text not null,
  "createdAt" timestamp default now()
);

-- 요약표를 이루는 줄 하나하나.
-- "ledgerId"가 있으면 기존 장부 내역에서 고른 줄(그 내역과 연결돼있음),
-- 없으면 사용자가 직접 입력한 줄(부가세환급 10% 같은 계산값 등)이다.
create table if not exists "LedgerReportItems" (
  id bigint generated by default as identity primary key,
  "reportId" bigint references "LedgerReports"(id) on delete cascade not null,
  label text not null,
  amount numeric not null,
  notes text,
  "ledgerId" bigint references "Ledger"(id) on delete set null,
  "sortOrder" integer not null default 0
);

create index if not exists "LedgerReports_bldId_idx" on "LedgerReports" ("bldId");
create index if not exists "LedgerReportItems_reportId_idx" on "LedgerReportItems" ("reportId");

-- 다른 테이블들과 같은 보안 모델: RLS를 켜고 정책은 하나도 안 만든다.
-- => 브라우저(anon/authenticated)는 전부 거부, 서버(service_role)만 접근 가능.
-- 쓰기는 항상 /api/ledgerReports(service_role)를 거치고, 거기서 bldId가
-- 내 가족(ownerId) 소유인지 매번 확인한다.
alter table "LedgerReports"      enable row level security;
alter table "LedgerReportItems"  enable row level security;

-- ---------------------------------------------------------------------
-- 확인
-- ---------------------------------------------------------------------
select tablename, rowsecurity
from pg_tables
where schemaname = 'public' and tablename in ('LedgerReports', 'LedgerReportItems');
