-- 건물 정보
-- ownerId: 이 건물이 속한 "가족(워크스페이스)"의 대표 계정 UID.
-- 대표 본인은 auth.uid() 그대로, 가족회원은 로그인 시 user_metadata.familyOwnerId를 이걸로 채운다.
-- 서로 다른 ownerId끼리는 완전히 독립된 데이터로 취급된다 (건물/일정/장부 전부).
create table "Buildings" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  address text,
  "bldName" text,
  "mainPurps" text,
  floor text,
  "platArea" text,
  "totArea" text,
  "useAprDay" text
);

-- 계약(임차) 정보
create table "Contracts" (
  id bigint generated by default as identity primary key,
  "contractDate" text,
  "contractPeriod" text,
  "roomNumber" text,
  name text,
  phone text,
  deposit numeric,
  rent numeric,
  vat numeric,
  "managementFee" numeric,
  "bldId" bigint references "Buildings"(id) on delete cascade
);

-- 일정
create table "Schedule" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  start timestamp,
  "end" timestamp,
  description text,
  notes text,
  rept integer,
  allday boolean default true,
  "bldId" bigint references "Buildings"(id) on delete cascade
);

-- 건물별 입출금 장부
create table "Ledger" (
  id bigint generated by default as identity primary key,
  "bldId" bigint references "Buildings"(id) on delete cascade,
  date date,
  purpose text,
  income numeric,
  expense numeric,
  "interestRate" numeric,
  "interestAmount" numeric,
  "borrowedDays" integer,
  notes text,
  "createdAt" timestamp default now()
);

-- 반복 일정 템플릿: 매월 특정 날짜에 자동으로 Schedule 항목을 만들어낸다.
-- (매일 도는 크론이 lastGeneratedMonth를 보고, 이번 달에 아직 안 만들었으면 하나 생성한다)
create table "ScheduleTemplates" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  "bldId" bigint references "Buildings"(id) on delete cascade,
  description text,
  notes text,
  "dayOfMonth" integer not null,
  active boolean default true,
  "skipHoliday" boolean default false,
  "lastGeneratedMonth" text,
  "createdAt" timestamp default now()
);

-- 반복 장부 템플릿: 매월 특정 날짜에 자동으로 Ledger 항목을 만들어낸다.
create table "LedgerTemplates" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  "bldId" bigint references "Buildings"(id) on delete cascade not null,
  purpose text,
  income numeric,
  expense numeric,
  "interestRate" numeric,
  "interestAmount" numeric,
  "borrowedDays" integer,
  notes text,
  "dayOfMonth" integer not null,
  active boolean default true,
  "skipHoliday" boolean default false,
  "lastGeneratedMonth" text,
  "createdAt" timestamp default now()
);

-- 회원 프로필은 별도 테이블 없이 Supabase Auth의 user_metadata를 사용한다.
-- (signup 시 supabase.auth.signUp의 options.data로 userId/name을 같이 저장)

-- 웹 푸시 구독 정보 (브라우저/기기별로 1개씩)
create table "PushSubscriptions" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  "createdAt" timestamp default now()
);

-- 가족 초대코드: 이메일로 신규 가입할 때 이 코드를 입력하면 발급자(ownerId)의 가족으로 합류한다.
-- 코드를 입력하지 않으면 새로운 가족(=새 워크스페이스)의 대표로 가입한다.
-- 코드 하나당 가족코드 공유 로그인 계정 하나 (family-{code}@familycode.internal, 비밀번호=코드)도 함께 대응된다.
create table "InviteCodes" (
  id bigint generated by default as identity primary key,
  "ownerId" uuid not null,
  code text unique not null,
  "createdByEmail" text,
  "usedByEmail" text,
  "usedAt" timestamp,
  "memberName" text,
  "revoked" boolean default false,
  "createdAt" timestamp default now()
);
