-- 건물 정보
create table "Buildings" (
  id bigint generated by default as identity primary key,
  address text,
  "bldName" text,
  "mainPurps" text,
  floor text,
  "platArea" text,
  "totArea" text,
  "useAprDay" text
);

-- 계약(임차) 정보
create table "Contracts" (
  id bigint generated by default as identity primary key,
  "contractDate" text,
  "contractPeriod" text,
  "roomNumber" text,
  name text,
  phone text,
  deposit numeric,
  rent numeric,
  vat numeric,
  "managementFee" numeric,
  "bldId" bigint references "Buildings"(id) on delete cascade
);

-- 일정
create table "Schedule" (
  id bigint generated by default as identity primary key,
  start timestamp,
  "end" timestamp,
  description text,
  notes text,
  rept integer,
  allday boolean default true,
  "bldId" bigint references "Buildings"(id) on delete cascade
);

-- 건물별 입출금 장부
create table "Ledger" (
  id bigint generated by default as identity primary key,
  "bldId" bigint references "Buildings"(id) on delete cascade,
  date date,
  purpose text,
  income numeric,
  expense numeric,
  "interestRate" numeric,
  "interestAmount" numeric,
  "borrowedDays" integer,
  notes text,
  "createdAt" timestamp default now()
);

-- 반복 일정 템플릿: 매월 특정 날짜에 자동으로 Schedule 항목을 만들어낸다.
-- (매일 도는 크론이 lastGeneratedMonth를 보고, 이번 달에 아직 안 만들었으면 하나 생성한다)
create table "ScheduleTemplates" (
  id bigint generated by default as identity primary key,
  "bldId" bigint references "Buildings"(id) on delete cascade,
  description text,
  notes text,
  "dayOfMonth" integer not null,
  active boolean default true,
  "skipHoliday" boolean default false,
  "lastGeneratedMonth" text,
  "createdAt" timestamp default now()
);

-- 반복 장부 템플릿: 매월 특정 날짜에 자동으로 Ledger 항목을 만들어낸다.
create table "LedgerTemplates" (
  id bigint generated by default as identity primary key,
  "bldId" bigint references "Buildings"(id) on delete cascade not null,
  purpose text,
  income numeric,
  expense numeric,
  "interestRate" numeric,
  "interestAmount" numeric,
  "borrowedDays" integer,
  notes text,
  "dayOfMonth" integer not null,
  active boolean default true,
  "skipHoliday" boolean default false,
  "lastGeneratedMonth" text,
  "createdAt" timestamp default now()
);

-- 회원 프로필은 별도 테이블 없이 Supabase Auth의 user_metadata를 사용한다.
-- (signup 시 supabase.auth.signUp의 options.data로 userId/name을 같이 저장)

-- 웹 푸시 구독 정보 (브라우저/기기별로 1개씩)
create table "PushSubscriptions" (
  id bigint generated by default as identity primary key,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  "createdAt" timestamp default now()
);

-- 가족 초대코드: 이 테이블에 발급된 코드가 하나라도 있으면
-- 그 이후 신규 가입은 유효한(미사용) 코드가 있어야만 허용된다.
-- 코드 하나당 가족회원 계정 하나 (family-{code}@familycode.internal, 비밀번호=코드)가 대응된다.
create table "InviteCodes" (
  id bigint generated by default as identity primary key,
  code text unique not null,
  "createdByEmail" text,
  "usedByEmail" text,
  "usedAt" timestamp,
  "memberName" text,
  "revoked" boolean default false,
  "createdAt" timestamp default now()
);
