import "./globals.css";
import ClientLayout from "@/components/layout";""
import localFont from "next/font/local";
import css from "./layout.module.css";
import AppSidebar from '@/components/appSidebar/appSidebar'; // 클라이언트 컴포넌트 불러오기
import { SidebarProvider } from '@/components/ui/sidebar';
const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html>
			<body>
			<SidebarProvider>
				<AppSidebar/>
				<main className={css.main}>
					<ClientLayout>
						{children}
					</ClientLayout>
				</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
