import "./globals.css";
import ClientLayout from "@/components/layout";""
import localFont from "next/font/local";
import css from "./layout.module.css";
import { Provider } from 'react-redux'; // react-redux에서 Provider 임포트

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
        <body>
            <header className={css.header}>
                <nav>Navigation Bar</nav>
            </header>
            <aside className={css.aside}>
            <a href="/rsms">Go to rsms</a>
            <a href="/">Go to List</a>
            <a href="/">Go to List</a>
            </aside>
            <main className={css.main}>
                <ClientLayout>
                    {children}
                </ClientLayout>
            </main>
            <footer className={css.footer}>
                Footer
            </footer>
        </body>
    </html>
);
}
